language: go

go:
  - 1.11.x
  - 1.10.x

go_import_path: github.com/gluster/gogfapi

dist: xenial
addons:
  apt:
    update: true
    packages:
      - glusterfs-common

services:
  - docker

before_script:
  - bash -x test_setup.sh

script:
  - go test -v ./...
